using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FormalLang5sem
{
    class MainProgram
    {
        static void Main(string[] args)
        {
            PrintExplanation();
        }


        private static void PrintExplanation()
        {
            Console.WriteLine("(c) Sasha Plotnikov Production, 2018");
            Console.WriteLine();
            Console.WriteLine("__________________________________");
            Console.WriteLine("This application solves the following problem:");
            Console.WriteLine("Input: 1) context-free grammar G = (Z, N, P),");
            Console.WriteLine("where Z - alphabet, N - nonterminals, P - production rules;");
            Console.WriteLine("2) finite automaton (as graph) R = (E, V, L), whrere ");
            Console.WriteLine("E - edges, V - vertices, L is contained in Z, E = V x L x V;");
            Console.WriteLine("Output: all triplets (i, N[k], j), where i, j are elements of V");
            Console.WriteLine("and exists path p in R and N[k] in N: w(p) is an element of L(G, N[k]),");
            Console.WriteLine("where w(p) is word formed by p, L(G, N[k]) is the language");
            Console.WriteLine("generated by G with start symbol N[k]");
            Console.WriteLine("__________________________________");
        }
    }
}
